# Generated by Django 4.0.4 on 2022-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ImageField(blank=True, upload_to='order_attachments'),
        ),
    ]
