# Generated by Django 4.0.4 on 2022-07-30 18:08

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ImageField(blank=True, upload_to='order_attachments', validators=[orders.models.validate_image], verbose_name='Image'),
        ),
    ]
